[#236] Fix Pipeline failure Test # 1438
We moved pipelines to a local machine outside of Gitlab, and the pipelines started failing for the GUI with this signature:

```
AssertionError: expected false to be true
    at Context.it (/YDBGUI/wwwroot/test/test_files/server/z-locks-manager.js:369:34)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

For example, in https://gitlab.com/YottaDB/UI/YDBGUI/-/jobs/3157764972.

This was a race issue due to the use of mupip stop. Added a delay of
100ms before checking mupip stop really stopped.

Took time to develop a way to debug a single test: The orignal command
`docker run --rm -v $PWD/wwwroot:/YDBGUI/wwwroot:rw yottadb/yottadbgui
test` will still run all the tests; but now you can specify a directory
or a single js file to run, as in `docker run --rm -v $PWD/wwwroot:/YDBGUI/wwwroot:rw yottadb/yottadbgui test wwwroot/test/test_files/server/z-locks-manager.js`.

Also removed a stray console.dir in the sam test file edited here.